# Generated by Django 3.2.7 on 2021-09-30 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0001_initial'),
        ('trayectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('estado', models.CharField(choices=[('0', 'NO INICIADO'), ('1', 'EN TRAYECTO'), ('2', 'FINALIZADO'), ('3', 'ABORDANDO')], max_length=1, verbose_name='Estado')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buses.bus')),
                ('trayecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trayectos.trayecto')),
            ],
        ),
    ]
