# Generated by Django 3.2.8 on 2021-10-08 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trayectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=255, verbose_name='Apellido')),
                ('documento', models.CharField(max_length=50, verbose_name='Documento')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('puesto', models.IntegerField(verbose_name='Puesto')),
                ('trayecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trayectos.trayecto', verbose_name='Trayecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['usuario', 'trayecto', 'documento'],
            },
        ),
    ]
