# Generated by Django 3.2.8 on 2021-10-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trayectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trayecto',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
