# Generated by Django 3.2.8 on 2021-10-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trayectos', '0002_alter_trayecto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trayecto',
            name='fecha',
            field=models.DateField(help_text='Escriba la fecha en formato dd/mm/aaaa ejemplo 01/01/2021', verbose_name='Fecha DD/MM/AAA'),
        ),
        migrations.AlterField(
            model_name='trayecto',
            name='hora',
            field=models.TimeField(help_text='Escriba la hora de la forma HH:MM:SS en formato de 24 horas ejemplo 10:00:00', verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='trayecto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
