# Generated by Django 3.2.7 on 2021-09-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('numeroPasajeros', models.IntegerField(verbose_name='Numero de pasajeros')),
                ('wc', models.BooleanField(default=False, verbose_name='Tiene Baño')),
                ('wifi', models.BooleanField(default=False, verbose_name='Tiene Wi-Fi')),
                ('aireAcondicionado', models.BooleanField(default=False, verbose_name='Tiene Aire Acondicionado')),
            ],
        ),
    ]
