# Generated by Django 3.2.7 on 2021-10-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='document',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Celular'),
        ),
    ]
