# Generated by Django 3.2.7 on 2021-09-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('documento', models.CharField(max_length=50, unique=True, verbose_name='Documento')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha nacimiento')),
                ('celular', models.CharField(max_length=50, verbose_name='Celular')),
                ('genero', models.CharField(choices=[('0', 'HOMBRE'), ('1', 'MUJER'), ('2', 'OTRO')], max_length=1, verbose_name='Genero')),
            ],
        ),
    ]
