# Generated by Django 3.2.8 on 2021-10-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=30, verbose_name='Origen')),
                ('destino', models.CharField(max_length=30, verbose_name='Destino')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('puestos', models.IntegerField(verbose_name='Puestos')),
            ],
            options={
                'verbose_name': 'Trayecto',
                'verbose_name_plural': 'Trayectos',
                'ordering': ['fecha', 'hora', 'origen', 'destino'],
            },
        ),
    ]
