# Generated by Django 3.2.7 on 2021-10-01 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
        ('usuarios', '0002_alter_usuario_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.persona'),
        ),
    ]
