# Generated by Django 3.2.7 on 2021-10-01 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
